# Generated by Django 2.2.5 on 2019-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(default=4)),
                ('tasks', models.IntegerField(default=0)),
            ],
        ),
    ]
