# Generated by Django 2.2.5 on 2019-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Server Name'),
            preserve_default=False,
        ),
    ]
