# Generated by Django 2.2.5 on 2019-09-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='tasks',
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_processes', to='servers.Server')),
            ],
        ),
    ]
