# Generated by Django 2.2.5 on 2019-09-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20190911_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='expiry',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
