# Generated by Django 2.2.5 on 2019-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_process_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
