# Generated by Django 2.2.5 on 2019-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20191029_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='max_ram',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='server',
            name='min_ram',
            field=models.IntegerField(default=1),
        ),
    ]
