# Generated by Django 2.2.5 on 2019-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20191030_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='ram',
            field=models.FloatField(),
        ),
    ]
