# Generated by Django 2.2.5 on 2019-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_auto_20191030_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
