# Generated by Django 2.2.5 on 2019-10-31 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_auto_20191031_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='sla',
        ),
        migrations.RemoveField(
            model_name='process',
            name='start',
        ),
    ]
