# Generated by Django 2.2.5 on 2019-10-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_auto_20191031_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='sla',
            field=models.IntegerField(default=1000),
        ),
    ]
